# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c08c06f626fc01f435a0ce28b678345314e4a18a4a5f50fdf99f3fc78a8299f3f465c6207bccb54821d55af8b63097c9d60356b11aec0ceaaf395fb67c68894d

test:
  secret_key_base: e072549ed416a868218a15cb38296142ed532b4f0fe6b0d552df25473feaf013318c8c5fa050622b383549b8a296b368e822266079bec3e398e76a0bde6f75e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
